config/routes.rb
Rails.application.routes.draw do
  get 'project/index'
  get 'project/dashboard'
  post 'project/create'


  root 'project#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates :name, :description, :state, presence: true
    enum state: [:proposal, :in_progress, :finished]
    scope :search, ->(param) {where(state: param)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  def index
    @project = Project.new
    @states = Project.states.keys.to_a
  end

  def dashboard
    return @project = Project.all unless params.has_key?(:s) && params[:s].present?
    @project = Project.search(params[:s]) 
  end

  def create
    @project = Project.create!(project_params)
    @project.save

  end

  def project_params
    params.require(:project).permit(:name, :description, :start, :end, :state)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="<%= project_index_path %>">Index<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= project_dashboard_path %>">Dashboard</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyects</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

  </head>

  <body>
   <%= render '/layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/project/create.html.erb
  
<% if @project.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project
from being saved:</h2>

    <ul>
    <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
</div>
<%= link_to 'Manage another project', project_index_path %>
<%= link_to 'Check other projects', project_dashboard_path %>
<% else %>
<h1> Your project was successfully saved! </h1>
<%= link_to 'Manage another project', project_index_path %>
<%= link_to 'Check other projects', project_dashboard_path %>
<% end %>

app/views/project/dashboard.html.erb
<form class="form-search">
    <select name="s"> 
        <option value="">Todos</option>
        <option value="proposal">Propuesta</option>
        <option value="in_progress">En progreso</option>
        <option value="finished">Termino</option>
    </select>
    <button type="submit"> Search</button>
</form>


<table class="table">
  <thead>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Descripcion</th>
      <th scope="col">Comienzo</th>
      <th scope="col">Termino</th>
      <th scope="col">Estado</th>
    </tr>
  </thead>
  <tbody>
  <% @project.each do |p| %>
    <tr>
      <th scope="row"><%= p.name %></th>
        <td><%= p.description %></td>
        <td><%= p.start %></td>
        <td><%= p.end %></td>
        <td><%= p.state %></td>
    </tr>
     <% end %>
  </tbody>
</table>

app/views/project/index.html.erb
<div class="container">
    <div class="title">
     <h1>Add a new project</h1>
    </div>

    <div class="form-with">
      <ul>
       <%=  form_with(model: @project, url: project_create_path, local: true) do |f| %>
        <li>
            <%= f.label :name, "Name" %>
            <%= f.text_field :name, placeholder: "Enter a name", size: "30x5" %>
        </li>
        <li>
            <%= f.label :name, "Description" %>
            <%= f.text_area :description, 
                placeholder: "Add a full description of the project",
                size: "40x5" 
            %>
        </li>
        <li>
            <%= f.label :name, 'Start on' %>
            <%= f.date_select :start %>
        </li>
        <li>
            <%= f.label :name, "End on" %>
            <%= f.date_select :end %>
        </li>
        <li>
            <%= f.label :state, "Estado" %>
            <%= f.select :state, options_for_select(@states) %>
        </li>
      </ul>
        <button type="submit"> Save</button>
       <% end %>
    </div>
</div>